### ISSUE TITLE
The apis are not CORS enabled

### ISSUE THREAD

**Issue by Vinod-Sutar** [MapmyIndia/mapmyindia-rest-api#2]
I am accessing the API but the CORS is blocking the connection. 
Can the API's be CORS enabled?
Can this be quickly solved.?

Thanks

**Comment by MapmyIndia-Maps** [comment]
Hi Vinod,
  
We strongly suggest you to use any backend technology for accessing MapmyIndia REST APIs.
Due to security reasons, the default policy is to keep CORS services blocked for all the users.

However, if you wish to use CORS for these RESTful services, please write us at [apisupport@mapmyindia.com](mailto:apisupport@mapmyindia.com) with your detailed use-case (on how you wish to utilize these APIs within your solution), and we will process your request for CORS-enabling. 

Regards
MapmyIndia
(CE Info Systems Pvt Ltd)
