### ISSUE TITLE
auto suggest

### ISSUE THREAD

**Issue by NightFury010497** [MapmyIndia/mapmyindia-rest-api#6]
as per the suggested I tried hitting the api using postman 
![image](https://user-images.githubusercontent.com/56355704/77527544-52c38200-6eb2-11ea-8ba5-0905dfa82ab6.png)
This is the Error I got.

**Comment by ImCarrot** [comment]
@NightFury010497  The problem is quite trivial, you seem to have passed in an incorrect sized access token (Most likely a copy paste error). To resolve this make sure the below:

- You're generating your access token using the `clientId` and `clientSecret` and following the official documentation of the [OAuth call here.](https://www.mapmyindia.com/api/advanced-maps/doc/authentication-api.php)
- You're passing in the access token generated from the above point as the `Authorization` header. The format looks like: `Bearer 0XXXXXXf-dXX0-4XX0-8XXa-eXXXXXXXXXX6`. 

Note: I've substituted the characters of the access token with `X` but the length remains the same. Just so that you can make out in case the there is a copy paste error.
